application: geeklatte
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /font
  static_dir: static/font
- url: /img
  static_dir: static/img
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
